### ISSUE TITLE
High CPU on startup

### ISSUE THREAD

**Issue by garyemerson** [ForestMist/sprucemarks#14]
Sprucemarks often uses unreasonably high CPU when I start up chrome (high 90%). I haven't been able to work around this issue so I unfortunately had to remove the extension. I have ~800 bookmarks so perhaps that is a contributing factor.

OS: Microsoft Windows 10 Enterprise, Version 10.0.16299 Build 16299
Chrome: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by ForestMist** [comment]
Ooh juicy.

How did you track the CPU usage of Sprucemarks? I'd love to do the same on my machines and see if I get the same results.

**Comment by garyemerson** [comment]
I just peeked at the chrome Task Manager which breaks down resource stats for each tab and extension. I'll see if I can create a minimal and consistent repro, right now I have a few other extensions installed including the [iCloud bookmarks extension](https://chrome.google.com/webstore/detail/icloud-bookmarks/fkepacicchenbjecpbpbclokcabebhah).

**Comment by ForestMist** [comment]
Sprucemarks says 0.1 CPU whenever I open the Task Manager. It does take me a few seconds to get to that screen when I do a fresh start of Chrome though.

The 0.1 CPU I'm seeing on my machine makes sense because behind the scenes, Sprucemarks is checking to see if anything needs to be sorted and in my case, nothing does because Sprucemarks fixed everything the last time Chrome was open.

If Sprucemarks is constantly trying to sort or fight against another extension that is also changing the sort order of bookmarks then yes, I would expect really high CPU usage until Sprucemarks triggers a "give up on this bookmark folder" mode. That give up period is temporary and Sprucemarks will try again to sort that folder again in the future.

It would be a good test to disable Sprucemarks then monitor Task Manager on startup to see what happens. Do that a few times in case one of the other extensions is busy re-sorting bookmarks.

Then disable all extensions but Sprucemarks, use the Task Manager and restart Chrome a few times to make sure things settle down. You should get to a point where Sprucemarks is using near 0 CPU on startup.

If you find that running just one or a few extensions at a time works great, it might be fun to selectively turn on extensions one by one, restarting Chrome each time, until you find the extensions that are not playing nice with each other.

I've never used the "iCloud bookmarks extension" but I do use the built-in Chrome sync option to sync bookmarks between my Mac, Windows, and iOS devices. Works great although sometimes the sync is not quite instantaneous. They have been greatly improving the speed over the years though. Not sure if that will meet your syncing needs but if it does, it means one less extension to have installed and that is always a good thing. ^_^
