### ISSUE TITLE
Sort bookmarks bar by usage?

### ISSUE THREAD

**Issue by orschiro** [ForestMist/sprucemarks#18]
@ForestMist thanks for your extension! This sounds super promising for what I want to do. 👍🙃

Basically, is there a way to sort the bookmarks bar automatically based on usage, i.e. frequency of accessing those bookmarks?

Thank you! ❤

**Comment by ForestMist** [comment]
Thanks. ^_^

I don't think so because the bookmark object for each individual bookmark does not seem to track that. More info at https://developer.chrome.com/extensions/bookmarks#type-BookmarkTreeNode

If you could figure out when someone clicked a bookmark (not sure), you could log that to your own database and then resort bookmarks based on that. That kind of solution is probably not worth all the effort though. :o

**Comment by orschiro** [comment]
> If you could figure out when someone clicked a bookmark (not sure), you could log that to your own database and then resort bookmarks based on that. That kind of solution is probably not worth all the effort though. :o

This sounds indeed very complicated. 😅

Well, maybe keep this open and someone else has an idea perhaps?

Thanks for your reply!

**Comment by ForestMist** [comment]
If the Chrome folks added that metric it would be easy for Sprucemarks or any other bookmark focused extension for Chrome to consume it.

Nothing to do on this issue for me so marking as resolved.

**Comment by orschiro** [comment]
I am going to suggest that upstream! 👍🙃

-
