### ISSUE TITLE
Why can’t we sort by URL

### ISSUE THREAD

**Issue by deepakjois** [ForestMist/sprucemarks#3]
I like my bookmarks sorted by the URL of the site. Can Sprucemarks do that? If not, is it possible to add that as a feature?

**Comment by ForestMist** [comment]
Sprucemarks doesn't currently sort by URL and the chance of that feature making it into production is quite honestly pretty low. At least, it is for now since URL sorting is not a common request. This could change if enough people want it.

On to happier news though!

Adding URL sorting is actually pretty easy. Easy enough that I've created a [sort-by-url](https://github.com/ForestMist/sprucemarks/tree/sort-by-url) branch for you. Check out commit f22104123dedcc88349bd0aa50763e198afdd97e specifically and you'll see that it didn't take too much code to accomplish.

To use this specialized version of Sprucemarks:

- Download the [sort-by-url](https://github.com/ForestMist/sprucemarks/archive/sort-by-url.zip) branch.
- Unzip it to a location on your hard drive.
- Chrome &gt; Preferences &gt; Extensions
- Disable the existing Sprucemarks extension.
- Enable Developer Mode
- Load Unpacked Extension
- Find the deploy folder under the location you unzipped the special branch to and click select.

Now you can set the new URL sorting options for Sprucemarks, hit save, and enjoy.

![new-url-sorting-options](https://cloud.githubusercontent.com/assets/1933203/15906877/a675c030-2d6f-11e6-8cf8-f57e0b1cbf33.png)

If you like how this all works then I would recommend forking Sprucemarks so it becomes your own repository. Then you could simply merge any interesting updates in the future from the main repo to yours. Updates don't happen too often since Sprucemarks is very stable at this point. Maintenance requirements should be quite low.

This is all optional of course. Just wanted to give you a better option than "no", even if it required a little bit of work. ^_^

Cheers!

P.S. - I may delete the sort-by-url branch at some indeterminate point in the future. Recommend forking it sooner than later if you think it may ever be useful to you.

**Comment by deepakjois** [comment]
Thanks a lot for the detailed response. That really helps. I can definitely setup a private copy of SpruceMarks. I will try it and report back.

However, I am not convinced that sorting by URL is _not_ a common request. I have been doing a survey of bookmark sorting extensions in chrome, and none of them support this feature. SpruceMarks is on Github, so at least I can report it as an issue. If you search Google for [‘chrome sort bookmarks’](https://www.google.co.in/search?q=chrome+sort+bookmarks+by+url), you will see quite a few links where people are wondering how to do this. A lot of the responses are misleading or just plain wrong. There is a link that leads to a [Windows app](http://www.technospot.net/blogs/sort-chrome-bookmarks/) that sorts Chrome bookmarks externally (I don’t use Windows so I cannot verify how well it works). So I believe there is definitely a need for this feature, and it is a pity that it is not available. Initially, I thought it was due to a technical limitation. But like you demonstrated, that is not the case.

I think there is a great opportunity here for SpruceMarks to implement this feature and benefit a bunch of users. Not everybody is going to come to Github and report an issue.

Thank you again for your efforts.

**Comment by deepakjois** [comment]
Just as an example. I bookmark a lot of YouTube videos over time to watch them later. It would be nice to have them sorted together so that I can view them all at once when I want to access them. Such a thing is only possible if I sort by domain/url.

**Comment by deepakjois** [comment]
The sort-by-url branch works beautifully. Here is a screenshot of my Other Bookmarks now. Exactly what I was looking for.

![screenshot 2016-06-09 09 12 15](https://cloud.githubusercontent.com/assets/5342/15918227/53b9c63a-2e22-11e6-85db-759c9dfd15e9.png)

**Comment by ForestMist** [comment]
That does look pretty decent with all the same site bookmarks grouped!

You are correct that not everyone will come to GitHub. Those that do post here, or in a comment on the Chrome Web Store, or reach out to me on Twitter, etc... get a huge boost in their influence precisely because not everyone will do so.

With that being said, I'm going to ask around on all my social media to see if anyone else is interested in URL sorting and point them to this thread. I encourage you to do the same because anyone who makes the effort to communicate is speaking up for not just themselves but a large chunk of users that may be wishing for something in silence.

Super happy the sort-by-url branch is working for you. ^_^

**Comment by ForestMist** [comment]
Good news! The sort-by-url branch has been merged into master and will go live to the Chrome Web Store a bit later today. ^_^
