### ISSUE TITLE
There should be an option for treating http and https as the same

### ISSUE THREAD

**Issue by aa3993** [ForestMist/sprucemarks#9]
or simply disregarding http and https or even the subdomain so that it only sorts according to the main address component which is the domain name.

**Comment by ForestMist** [comment]
Here is the current code related to URL sorting.

```
value = o.url.toLowerCase()
value = value.replace('http://', '').replace('https://', '').replace('ftp://', '').replace('chrome://', '').replace('www.', '')
```

The URL is lowercased and then normalized by removing `http://`, `https://`, `ftp://`, `chrome://`, and `www.`.

I quite like this logic because I think the protocol (http for example) should not be part of the sorting. I also like removing the `www.` portion otherwise you could just have a bunch of bookmarks jammed up in the W section and that wouldn't be very useful.

**Comment by aa3993** [comment]
Oh ok didn't realize that it is already implemented. Thanks for the extension btw.

**Comment by ForestMist** [comment]
Sure thing. Happy it helps. ^_^

I think I going to keep subdomains as is for now but I do see where it could be helpful to lump all Microsoft domains a.microsof.com, b.microsoft.com, c.microsoft.com together.
